Feature/hud
SPCdelta/DeltaEngine pull request #106
Opened 2024-12-08 14:39 UTC by jwmying

Heel veel hardcoded values voor nu. GameSpeed is nog niet volledig functioneel maar dat komt wel

closes #104

2024-12-08 15:06 UTC, Enyuuus requested changes

2024-12-09 10:38 UTC, CharlotteK0250 commented on DeltaEngine/DeltaEngine.vcxproj
Kan het zijn dat je het project nog niet op all vonfigurations hebt staan?

2024-12-09 10:40 UTC, CharlotteK0250 commented on DeltaEngine/DeltaEngine.vcxproj
want bij de andere includes zijn er geen specifieke debug en release configuration conditions

2024-12-09 10:44 UTC, CharlotteK0250 commented on ValidationApp/src/Views/Components/HotbarComponent.cpp
> +	else
Misschien netter om er een else if van te maken ipv een else met een if erin

2024-12-09 10:46 UTC, CharlotteK0250 commented on ValidationApp/src/Views/Components/HotbarComponent.cpp
> +	if (result != _hotbar.end())
Je kan hier een return static_cast<Uint8>(std::distance(_hotbar.begin(), result)); in de if plaatsen met return UINT8_MAX; erbuiten/in de else

2024-12-09 10:48 UTC, CharlotteK0250 commented on ValidationApp/src/Views/HUDView.hpp
> +	Uint8 NUM_OF_COLS = 6;
kan NUM_OF_COLS een constexpr/static zijn?

2024-12-09 15:33 UTC, CharlotteK0250 approved these changes

2024-12-09 17:00 UTC, merged