GameSpeed
SPCdelta/DeltaEngine pull request #114
Opened 2024-12-11 14:19 UTC by jwmying

closes #109

2024-12-11 14:28 UTC, CharlotteK0250 approved these changes

2024-12-11 14:36 UTC, JrnJ requested changes

2024-12-11 14:36 UTC, JrnJ commented on DeltaEngine/Engine/Application.cpp
> +		std::string fps = "FPS: " + std::to_string(static_cast<int>((1.0f / Time::deltaTime)));
Je past framerate aan, niet snelheid, doe de deltime * snelheid ipv framerate * snelheid

2024-12-12 13:33 UTC, CharlotteK0250 approved these changes

2024-12-12 13:42 UTC, JrnJ approved these changes

2024-12-12 13:42 UTC, JrnJ commented on DeltaEngine/Engine/Core/Time.cpp
> +		throw std::exception{ "Multiplier value cannot be greater than 1." };
Wil je hier wel een exception gooien of gewoon niet zetten?

2024-12-12 13:47 UTC, merged